title: Himadri Chowdhury
position: Research Assistant
affiliation: Georgia Southern University
subtitle: "M.S. in Computer Science | Deep Learning Enthusiast"
email: himadrichowdhury172 (at) gmail (dot) com
keywords: minimal academic
github_link: https://github.com/himadri001
linkedin: https://linkedin.com/in/himadri-chowdhury-549820160
google_scholar: https://scholar.google.com/citations?hl=en&user=8L-5gbUAAAAJ
cv_link: ./assets/pdf/Himadri_Chy_Resume.pdf
avatar: ./assets/img/mypic.JPG
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: An industry experienced software engineer having keen research enthusiasm particularly in Computer Vision and Deep Learning
canonical: https://strata-academic.yyliu.net/
remote_theme: yaoyao-liu/strata-academic